### ISSUE TITLE
Sidebar is not working

### ISSUE THREAD

**Issue by SarangKumar** [Nexus-PES/NoteVault#5]
Sidebar functionality is note done properly, It should have a smooth open and close effect and will have all title of all the notes

**Comment by burhanharoon** [comment]
Hi @SarangKumar, can you assign this to me, I'll fix it and then create a PR. Sounds good?

**Comment by SarangKumar** [comment]
Yes sounds good. But there are a few requirements of this sidebar.
- it should be responsive. 
- in the desktop as well as on mobile screens it should show the sidebar icon. When the user click on that then only open that ribbon(that is currently there) and in that ribbon there should be one icon to open the notes that are created. You could refer to [obsidian](https://obsidian.md/)
- optionally you could use local storage to save the preference of the user. If want to have the ribbon(not the notes) enabled or disabled. 
- try to make it such that no merge conflicts occur. 

> by default sidebar ribbon should not be there and just the icon to open it should be there
When someone clicks on that icon then only make the sidebar ribbon visible. When is it visible it should push the contents, it should not be on top of other elements

Sound good? Also how much time will you take for this ?
